name: Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  hello-world:
    name: hello-world job
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Print message
      - shell: bash
      - run: echo "I am learning GitHub actions"